services:
  postgres:
    image: postgres:17.6-alpine
    container_name: cake_knife_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cake_knife_test
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: cake_knife_test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cake_knife_test
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init-db-mysql.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 2s
      timeout: 5s
      retries: 10
